sudo: false
services:
    - xvfb
before_script:
    - "export DISPLAY=:99.0"
language: python
install:
    - pip install -r requirements.txt
    - pip install coveralls
    - pip install matplotlib
python:
#    - "2.7"
#    - "3.4"
#    - "3.5"
    - "3.6"
    - "3.7"
#    - "3.8"   # pyfftw does not yet support 3.8
addons:
  apt:
    packages:
    - libfftw3-dev
script:
    - nosetests -v --with-coverage --cover-package=chebpy
after_success:
    - coveralls
