sudo: false
services:
    - xvfb
before_script:
    - "export DISPLAY=:99.0"
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
language: python
install:
    - pip install -r requirements.txt
    - pip install coveralls
    - pip install matplotlib
python:
#    - "2.7"
#    - "3.4"
#    - "3.5"
    - "3.6"
    - "3.7"
#    - "3.8"   # pyfftw does not yet support 3.8
addons:
  apt:
    packages:
    - libfftw3-dev
script:
    - nosetests -v --with-coverage --cover-package=chebpy
after_success:
    - coveralls
# for codecoverage on codeclimate.com
env:
  global:
    - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)
    - CODECLIMATE_REPO_TOKEN=[token]
    - CC_TEST_REPORTER_ID=[id]
 
