sudo: false
services:
    - xvfb
env:
  global:
    # codeclimate reporter ID
    - CC_TEST_REPORTER_ID=a28cfd4f5e103aa7d10816ece4062d8fe6bef88041b984abccddce0f3fb97cd5
before_script:
    - "export DISPLAY=:99.0"
    # fetch codeclimate test reporter
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build
language: python
install:
    - pip install -r requirements.txt
    - pip install coveralls
    - pip install matplotlib
python:
#    - "2.7"
#    - "3.4"
#    - "3.5"
    - "3.6"
    - "3.7"
#    - "3.8"   # pyfftw appears to not yet support 3.8
addons:
  apt:
    packages:
    - libfftw3-dev
script:
    - nosetests -v --with-coverage --cover-package=chebpy
after_success:
    - coveralls
# pipe results to codeclimate
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
