name: chebpy-binder
channels:
  - conda-forge
dependencies:
  # specify the Python version
  - python=3.8
  # install chebpy via conda-forge
  - chebfun
  # additional modules for convenience
  - scipy
  - pandas
  - matplotlib
  - seaborn
