version: '3'

tasks:
  uv:
    desc: Install uv and uvx
    cmds:
      - |
        # install uv and uvx
        curl -sSf https://astral.sh/uv/install.sh | sh > /dev/null 2>&1 || { echo "${RED}Installation failed!${RESET}" >&2; exit 1; }
        export PATH="$HOME/.local/bin:$PATH"

  install:
    desc: Install all dependencies using uv
    deps: [uv]
    cmds:
      - |
        # Check if .venv folder already exists
        if [ -d ".venv" ]; then
          printf "${BLUE}[INFO] Virtual environment already exists, skipping installation${RESET}\n"
        else
          # we need the virtual environment at least for the tests to work
          # even if we don't install anything
          
          # Create the virtual environment
          printf "${BLUE}[INFO] Creating virtual environment...${RESET}\n"
          
          # Create the virtual environment
          uv venv --python 3.12 || { printf "${RED}[ERROR] Failed to create virtual environment${RESET}\n"; exit 1; }
          
          if [ -f "pyproject.toml" ]; then
            printf "${BLUE}[INFO] Installing dependencies${RESET}\n"
            uv sync --all-extras --frozen || { printf "${RED}[ERROR] Failed to install dependencies${RESET}\n"; exit 1; }
          else
            printf "${YELLOW}[WARN] No pyproject.toml found, skipping install${RESET}\n"
          fi
        fi

  build:
    desc: Build the package using hatch
    deps: [install]
    cmds:
      - |
        if [ -f "pyproject.toml" ]; then
          uvx hatch build
        else
          printf "${YELLOW}[WARN] No pyproject.toml found, skipping build${RESET}\n"
        fi
