version: '3'

tasks:
  clean:
    desc: Clean generated files and directories
    cmds:
      - |
        printf " ${BLUE}[INFO] Cleaning project...${RESET}\n"
        git clean -d -X -f
        rm -rf dist build *.egg-info .coverage .pytest_cache
        printf " ${BLUE}[INFO] Removing local branches with no remote counterpart...${RESET}\n"
        git fetch --prune
        git branch -vv \
          | grep ': gone]' \
          | awk '{print $1}' \
          | xargs -r git branch -D 2>/dev/null || true
