# This file is part of the tschm/.config-templates repository
# (https://github.com/tschm/.config-templates).
#
# Action: Setup Project (composite action)
#
# Purpose: Bootstrap a Python project in GitHub Actions by:
#   - Installing Task, uv, and uvx into a local ./bin directory
#   - Optionally rendering the repository from a Copier template for tests
#   - Detecting presence of pyproject.toml and exposing it as an output
#   - Creating a virtual environment with uv and syncing dependencies
#
# Inputs:
#   - python-version: Python version used for the virtual environment (default: 3.12)
#
# Outputs:
#   - pyproject_exists: "true" if pyproject.toml exists, otherwise "false"
#
# Notes:
#   - Safe to run in repositories without pyproject.toml; dependency sync will be skipped.
#   - Used by workflows such as CI, Book, Marimo, and Release.

name: 'Setup Project'
description: 'Setup the project'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.12'

outputs:
  pyproject_exists:
    description: 'Flag indicating whether pyproject.toml exists'
    value: ${{ steps.check_pyproject.outputs.exists }}

runs:
  using: 'composite'
  steps:
    - name: Set up task, uv, uvx and the venv
      shell: bash
      run: |
        mkdir -p bin

        # Install Task
        curl -fsSL https://taskfile.dev/install.sh | sh -s -- -d -b ./bin

        # Install uv and uvx
        curl -fsSL https://astral.sh/uv/install.sh | UV_INSTALL_DIR="./bin" sh

        # Verify installations
        ./bin/task --version
        ./bin/uv --version
        ./bin/uvx --version

    - name: Render the project
      if: hashFiles('tests/resources/render.yml') != ''
      shell: bash
      run: |
        pip install copier

        # Render the current folder in-place
        copier copy . . \
          --data-file ./tests/resources/render.yml \
          --force \
          --overwrite \
          --quiet

        # Delete all remaining .jinja files
        find . -type f -name "*.jinja" -exec rm -f {} +

        # Delete all folders that still contain {{ ... }}
        find . -depth -type d -name "*{{*}}*" -exec rm -rf {} +

        ls -R

    - name: Check for pyproject.toml
      id: check_pyproject
      shell: bash
      run: |
        if [ -f "pyproject.toml" ]; then
          echo "exists=true" >> "$GITHUB_OUTPUT"
        else
          echo "exists=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Build the virtual environment
      shell: bash
      run: ./bin/uv venv --python ${{ inputs.python-version }}

    - name: "Build the virtual environment for ${{ github.repository }}"
      shell: bash
      run: |
        if [ -f "pyproject.toml" ]; then
          ./bin/uv sync --all-extras
        else
          echo "No pyproject.toml found, skipping package installation"
        fi
