# This file is part of the tschm/.config-templates repository
# (https://github.com/tschm/.config-templates).
#
# Action: Setup Project (composite action)
#
# Purpose: Bootstrap a Python project in GitHub Actions by:
#   - Installing Task, uv, and uvx into a local ./bin directory
#   - Optionally rendering the repository from a Copier template for tests
#   - Detecting presence of pyproject.toml and exposing it as an output
#   - Creating a virtual environment with uv and syncing dependencies
#
# Inputs:
#   - python-version: Python version used for the virtual environment (default: 3.12)
#     Can be overridden by setting PYTHON_DEFAULT_VERSION repository variable
#   - uv-extra-index-url: Extra index URL for uv (optional)
#
# Outputs:
#   - pyproject_exists: "true" if pyproject.toml exists, otherwise "false"
#
# Notes:
#   - Safe to run in repositories without pyproject.toml; dependency sync will be skipped.
#   - Used by workflows such as CI, Book, Marimo, and Release.

name: 'Setup Project'
description: 'Setup the project'

inputs:
  python-version:
    description: 'Python version to use'
    required: true
  uv-extra-index-url:
    description: 'Extra index URL for uv'
    required: false

outputs:
  pyproject_exists:
    description: 'Flag indicating whether pyproject.toml exists'
    value: ${{ steps.check_pyproject.outputs.exists }}

runs:
  using: 'composite'
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        version: "0.9.17"

    - name: Render the project
      if: hashFiles('tests/resources/render.yml') != ''
      shell: bash
      run: |
        pip install copier

        # Render the current folder in-place
        copier copy . . \
          --data-file ./tests/resources/render.yml \
          --force \
          --overwrite \
          --quiet

        # Delete all remaining .jinja files
        find . -type f -name "*.jinja" -exec rm -f {} +

        # Delete all folders that still contain {{ ... }}
        find . -depth -type d -name "*{{*}}*" -exec rm -rf {} +

        ls -R

    - name: Check for pyproject.toml
      id: check_pyproject
      shell: bash
      run: |
        if [ -f "pyproject.toml" ]; then
          echo "exists=true" >> "$GITHUB_OUTPUT"
        else
          echo "exists=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Build the virtual environment
      shell: bash
      run: uv venv --python ${{ inputs.python-version }}

    - name: "Sync the virtual environment for ${{ github.repository }} if pyproject.toml exists"
      shell: bash
      run: |
        if [[ -n "${{ inputs.uv-extra-index-url }}" ]]; then
          export UV_EXTRA_INDEX_URL="${{ inputs.uv-extra-index-url }}"
        fi

        if [ -f "pyproject.toml" ]; then
          uv sync --all-extras
        else
          echo "No pyproject.toml found, skipping package installation"
        fi
