name: Unit testing

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
        with-plot: [0, 1]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt install libfftw3-dev
          python -m pip install --upgrade pip
          if test "${{ matrix.with-plot }}" -eq "1"; then
            pip install ".[plot]"
          else
            pip install .
          fi
          pip install nose
      - name: Run tests
        run: |
          nosetests -v --where=tests/
