name: Unit testing

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
        matplotlib: [noplot, plot]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt install libfftw3-dev
          python -m pip install --upgrade pip
          if test "${{ matrix.matplotlib }}" -eq "plot"; then
            pip install ".[plot]"
          else  # noplot
            pip install .
          fi
          # install testing tools
          pip install nose "coverage[toml]" coveragepy-lcov
      - name: Run tests
        run: |
          nosetests -v --where=tests/ --with-coverage --cover-package=chebpy
          coveragepy-lcov --data_file_path .coverage --output_file_path lcov.info
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./lcov.info
